version: "3.3"
services:
  # --------------- DATABASES  ---------------
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure
