version: "3.3"
services:
  # --------------- DATABASES  ---------------
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure
  # --------------- SERVICES  ---------------
  project-service:
    build:
      context: project
    container_name: project-service
    ports:
      - 8082:8082
    environment:
      - SERVER_PORT=8082
      - SPRING_APPLICATION_NAME=project-service
    restart: always
  user-service:
    build:
      context: user
    container_name: user-service
    ports:
      - 8081:8081
    environment:
      - SERVER_PORT=8081
      - SPRING_APPLICATION_NAME=user-service
    restart: always
