version: "3.3"
services:
  # --------------- REDIS  ---------------
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PORT=6379
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    #    volumes:
    #      - "./neo4j/data:/data"
    restart: on-failure
  # --------------- SERVICES  ---------------
  eureka-service:
    build:
      context: eureka
    container_name: eureka-service
    ports:
      - 8761:8761
    environment:
      - SERVER_PORT=8761
      - SPRING_APPLICATION_NAME=eureka-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761
    restart: on-failure
  project-service:
    build:
      context: project
    container_name: project-service
    ports:
      - 8082:8082
    environment:
      - SPRING_APPLICATION_NAME=project-service
      - GATEWAY_SERVICE_NAME=gateway-service
      - EUREKA_SERVICE_NAME=eureka-service
      - NEO4J_NAME=neo4j
      - REDIS-NAME=redis
      - FRONTEND_SERVICE_NAME=frontend
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761
    depends_on:
      - eureka-service
    restart: on-failure
  user-service:
    build:
      context: user
    container_name: user-service
    ports:
      - 8081:8081
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - GATEWAY_SERVICE_NAME=gateway-service
      - EUREKA_SERVICE_NAME=eureka-service
      - NEO4J_NAME=neo4j
      - REDIS-NAME=redis
      - FRONTEND_SERVICE_NAME=frontend
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761
    links:
      - eureka-service
    depends_on:
      - eureka-service
    restart: on-failure
  gateway-service:
    build:
      context: gateway
    container_name: gateway-service
    ports:
      - 8090:8090
    environment:
      - SERVER_PORT=8090
      - SPRING_APPLICATION_NAME=gateway-service
      - PROJECT_SERVICE_NAME=project-service
      - USER_SERVICE_NAME=user-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761
      - FRONTEND_PORT=4200
    links:
      - eureka-service
    depends_on:
      - eureka-service
      - project-service
      - user-service
    restart: on-failure
#  frontend:
#    build:
#      context: frontend
#    ports:
#      - 4200:4200
#    restart: always
