server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      cache:
        ttl: 1s
      ribbon:
        enabled: false

eureka:
  client:
    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_NAME:localhost}:8761
